# Generated by Django 4.2.5 on 2023-09-05 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecoevents',
            new_name='Ecoevent',
        ),
    ]
