# Generated by Django 4.2.5 on 2023-09-07 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoevents', '0002_rename_ecoevents_ecoevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
